### ISSUE TITLE
refactor 'Reliability'

### ISSUE THREAD

**Issue by danieleades** [jhelovuo/RustDDS#125]
i think a similar refactor is possible for `Reliability` as for `Locator`. It doesn't make sense to have both `Reliability` and `ReliabilityKind` enums- this is just a hangover from the spec being written for languages that don't have discriminated unions. It's not totally obvious to me how to refactor the 'serializer' to do this though.

**Comment by jhelovuo** [comment]
If you grep through the source, you should be able to confirm that `ReliabilityKind` is only ever used during (de)serialisation.

The actual (de)serialisation format of Reliability QoS is by a struct definition [here](https://github.com/jhelovuo/RustDDS/blob/a70a3232dcc8657a7d929ac02ccae7635ca5f086/src/serialization/builtin_data_deserializer.rs#L592)  and a [duplicate here](https://github.com/jhelovuo/RustDDS/blob/a70a3232dcc8657a7d929ac02ccae7635ca5f086/src/serialization/builtin_data_serializer.rs#L889)

How to refactor:
Unify these two duplicate format definitions, as they must always agree. It is just fine that they live at the built-in serialiser level, because they are used only there. The `ReliabilityKind` definition should be placed also on the serialiser level, far away from `Reliability`.

**Comment by jhelovuo** [comment]
This issue seems outdated due to the great Discovery serialize/deserialize rewrite between 0.8.2 and 0.8.3.
