### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by jhelovuo** [jhelovuo/RustDDS#13]
Unit tests at the end of code modules are out of sync w.r.t. current implementation, so tests do not even compile. They should be updated to be compatible with current code.

**Comment by Bremys** [comment]
Hi, I wanted to get my feet wet with this project so I picked a unit test file and fixed its compilation errors.
I would like to make sure I have fixed it correctly and run the tests incrementally, that is, finish fixing a file and run it.
I currently can't do that since it demands all tests to compile, I haven't found online a way to make it work, any advice or experience with this issue?

**Comment by jhelovuo** [comment]
Not really. I think Cargo requires that all the unit tests compile before you can even try to run them. I did not try to verify this anywhere, so I could be wrong too.

One option is to just comment out unit tests in other modules, so you can incrementally fix them.

An easier exercise could be to fix the documentation code examples, as in #26 .

**Comment by jhelovuo** [comment]
Thank you again @Bremys . Atostek wishes to thank you for your contribution. We could send you a token of our appreciation. If you agree, please send your physical mail address via email, preferably with some proof that it is actually from you (the Github account), to juhana.helovuo@atostek.com .
