### ISSUE TITLE
Could not open user traffic listener: Os { code: 98, kind: AddrInUse, message: \"Address already in use\" }

### ISSUE THREAD

**Issue by maspe36** [jhelovuo/RustDDS#142]
Hey all,

I'm trying to write a toy rust binary to listen to another applications published messages. However when I attempt to listen on the domain id the other application is running on I get this error. 

`Could not open user traffic listener: Os { code: 98, kind: AddrInUse, message: \"Address already in use\" }`

I'm a bit confused by this because I'm able to have other applications in C++ and python participate at this domain id and subscribe to topics with no issue. I see in the docs [here](https://docs.rs/rustdds/0.6.1/rustdds/dds/struct.DomainParticipant.html#) that I should only have one domain per machine active, but I don't interpret that as I can't have multiple applications on the same machine using the same domain id. 

Am I missing something here?

**Comment by jhelovuo** [comment]
You should be able to run multiple domain participants on the same computer.

What is the other RTPS implementation you are running? Is this on Linux or some other OS?

**Comment by maspe36** [comment]
I'm using RTI Connext 5.3 on Ubuntu 18.04

**Comment by jhelovuo** [comment]
Congratulations, you have discovered a genuine bug. Or at least bad behaviour.

This should be now fixed in Version 0.6.2. Tested against RTI's Shapes Demo running on both the same and neighbour host. For some reason, RTI and RustDDS have problems discovering each other on the same host if RTI is already running when RustDDS is started, but the other way around works fine. Investigating this is left until later.

Does 0.6.2 work for you?

**Comment by maspe36** [comment]
Yup 0.6.2 works, thanks for the help!
