### ISSUE TITLE
Update to use mio 0.8.x

### ISSUE THREAD

**Issue by fgadaleta** [jhelovuo/RustDDS#203]

**Comment by jhelovuo** [comment]
This is non-trivial, because we depend also on [mio-extras](https://crates.io/crates/mio-extras) crate to get mio-pollable channels, and that is not available for mio 0.7.x or 0.8.x, because of features dropped from mio. Can you make this change and submit a pull request?

**Comment by wangxiaochuTHU** [comment]
Hello. I found this issue might be related to a previous Windows Problem, so I think I could post a user response here.

Months ago I accidently made RustDDS run on Windows with a minor patch. But recently when I tried it on my Windows again, it failed to work (Actually I was using it on Raspberries Linux during these months so this feedback is so late).

I made some investigation and finally found it might be Windows OS bug, which was not dealed with well by mio 0.6 (refer to mio 0.7.0, [Suspect Windows UDP operations](https://github.com/tokio-rs/mio/issues/1062), [Fix for windows selector locking mechanism](https://github.com/tokio-rs/mio/pull/1055) and [Fix udp wrong wouldblock's handling](https://github.com/tokio-rs/mio/pull/1066/files) ). 

I'm not 100% sure of this, since at last I find this fix is not easy to be applied on mio 0.6.23. Old `UdpSocket` contains little historical config state.  
```
// new, mio 0.7.0
pub struct UdpSocket {
    internal: Arc<Mutex<Option<InternalState>>>,
    io: net::UdpSocket,
}

// old, mio 0.6.0
pub struct UdpSocket {
    imp: Imp,
    registration: Mutex<Option<poll::Registration>>,
}
```
Just to let you know. 
Regards.

**Comment by Thomasdezeeuw** [comment]
Any thing I can do to help this move forward? Mio v0.6 is no longer supported (and hasn't been for a little while).

**Comment by jhelovuo** [comment]
The basic thing to do is to replace all uses of mio-0.6.x with mio-0.8 equivalents.
This is otherwise straightforward, but [mio-extras](https://crates.io/crates/mio-extras) is only supported up to mio-0.6.x. There is a crate [mio-misc](https://crates.io/crates/mio-misc) , which could be used to replace mio-extras, but that need to be confirmed somehow. Can you answer if mio-misc is a suitable replacement and do any better alternatives exist?

While doing the upgrade, it would be also worthwhile to investigate if almost the same work could be used to bring some async support to RustDDS, so that the library users could use some async runtime (e.g. Tokio) to do asynchronous DDS operations instead of using `.poll()` from mio.

**Comment by jhelovuo** [comment]
RustDDS 0.8 supports both mio-0.6 and mio-0.8 at the API.
